language: go
go:
  - 1.7.x
  - 1.8.x
  - tip
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
before_deploy:
  - go get github.com/mitchellh/gox
  - gox -os="linux windows darwin" -arch="amd64 386" -output="release/{{.Dir}}_{{.OS}}_{{.Arch}}" .
deploy:
  provider: releases
  api_key:
    secure: Jlnbbfi4l+egfcnQxeKckmMvZOLGIxN+ga9Zz5aKRm5gElXUPM2xFmt5TDIQ1nEDpVO6wcKYccB4a1WO0RtqZjIHoy0gZIP8MrIE0OwODy+JvN1sXSCpTKYq1omAErSxY3uZcKy6S7gN5QmGIiOtRPltwBRRTzQQLqXp1S7GwwBpigeFC3NjQfaFhb5V5psHCk04Befgx2U97uvAUWhCKmJfjZxEq9zGx5jt7RXUwBbmqn4qZuoL5bCSSm5k2TXTP8cjB5cuVtH9ToJ+CyFLFW2iX3J+iT+dkdrFqlb7fcqj+X5DWZQXOV55AagnmijVEQWCtPo0wK3jUdvfVBs8V4gQwp4AcDPmXnsYvZIPqCknhK5EvpnPmnj/sbniYS+IK5+xLkkyJwHMl6lxli3S14GViyIW7zDUzcK2VQHybJb9pTqz7nOAAJlk+drTkddUX2H+2UuyqkmDoT/F+pzfhB1FaNed7SIEllJRyHeYY1WlddfHtRHv3f9SvXxGUqVY74uo+27Fx4aSMd0UF+qayVe0phI3Y4/6JZHylxy3C1d9SXivQHJc8HFAaDdGaKh2XO+tdoz+sB9sTilcNESQJjZUFstSgeN0iqUh4KkkxnqNX5RUJIA3WVuYN1TFsseUox3JLG1rrJM2QZX/HaZrnQFGY4gmvtMpRRsHuawm6YQ=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    repo: theag3nt/httpecho
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.8
