language: go
go:
  - 1.15.x
  - 1.16.x
  - 1.17.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
before_deploy:
  - go get github.com/mitchellh/gox
  - gox -os="linux windows darwin" -arch="amd64 386" -output="release/{{.Dir}}_{{.OS}}_{{.Arch}}" .
deploy:
  provider: releases
  api_key:
    secure: HjoaCNLrK168rSFl9VnNWjKHU7lCY67bd8GVtL+PxJISlbuVZq9HVakG14vomIJ6wsbYXP93EKKUvPPs2XhlFz2xm2ijZWnntC+chZT20yq3Uu6ydSDD4RAN13k2c4H06yCWJDyx5z7xfadr0GtZrqI8gwYRQI5O/LCJzFvEbtRKha3eh24n1sOFqjpBHc4L8TZ3jgvyhZ5Oia2wr8u2nXH8x19tCvLAwKCkCw4M08m3jmZ6/CDBvcos6hhYStBEwRy6RMrbJA/2fmCZm6XICrHHIfelhJWWJEd2zR0N1WoGcItq5z/ISrssk72lVx8SevfiSnHyREhF76S7rVzQfKhkfEYP5yjf8tFKf4GByOKPyTjZNp4BMN9bRy6pNGYV2x40mXvprjJtWndy7Vho7HTn4TKkL7Rdy6agoJLMWoqR4REFxWeAjPbT/kK+DuKaLLn8wMNrFEM7Asnszfv1VgnIPTOIcGTNpuiSlL6P46dV3xkVqm1oeoarSEeOutyV4/9FQFmYWz5PiB21NcVtxsfzuFamJstKK26bp8HACZk7w3Jf2zBCeDde70IREqwTZaILSUn3s9aEpZIHZRhZpY7fTut9/OrGiIY9iERd7PBHCnkXfRwUeHzem84p5HCnosJ69qsQbjtMBT8kdk4XUZHda/1NmC9vlFL/BCdDlms=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    repo: theag3nt/httpecho
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.15
